version: '3.8'

services:
  file-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guestbook
    ports:
      - "8080:8080"
    environment:

    restart: always
